name: Deploy Quasar Frontend

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build Quasar app
        run: |
          cd frontend
          npx quasar build

      - name: Upload build to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "frontend/dist/spa/*"
          target: "/opt/shortner-link/frontend"

      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sudo systemctl reload nginx
